development:
  adapter: postgresql
  encoding: unicode
  database: radiant_island_development
  pool: 5
  host: localhost
  username: postgres
  password: 1234

test:
  adapter: postgresql
  encoding: unicode
  database: radiant_island_test
  pool: 5
  host: localhost
  username: postgres
  password: 1234